export type CharachterStories = {
    name: string;
    story: string;
};

export const charactherStories: CharachterStories[] = [
    {
        name: "Heinrich",
        story: "Sei nato nel 1897 ad Amburgo. A 17 anni hai iniziato a fare il marinaio, poco dopo ti hanno chiamato per andare sul fronte a combattere la prima guerra mondiale. Hai visto i tuoi nemici solo dalla trincea. Non sai se i colpi che hai sparato abbiano mai ucciso un altro uomo. Quando sei tornato ad Amburgo hai proseguito la tua carriera di marinaio. Quando, nel 1933, Hitler ha preso il potere, per cambiare aria hai cercato un lavoro al di là dell'oceano, senza riuscirci. La politica non ti è mai interessata e per questo non hai preso la tessera del partito. Ricordi bene quel giorno in cui Hitler venne nel porto di Amburgo a inaugurare una nave militare: non capisti la follia di quell'uomo con le braccia incrociate in mezzo alla folla, l'unico a non fare il saluto nazista. Nel 1938, con la guerra ormai alle porte, hai deciso di entrare nella polizia, sperando di non essere richiamato al fronte e di poter restare vicino alla tua famiglia. Ti hanno assegnato al Battaglione 101. Nel dicembre del 1941 ti hanno affibbiato il servizio di guardia in stazione, durante la deportazione di un migliaio di ebrei della tua città. Ma non ti è stato richiesto di accompagnare i deportati fino a destinazione, compito che ti avrebbe offerto la possibilità di viaggiare ma che è spettato ai tuoi compagni più alti in grado. Tu non hai mai fatto carriera: sei rimasto un poliziotto semplice. Adesso siamo nel 1942 e tu hai 45 anni. Il Battaglione 101 viene riorganizzato. La tua squadra è composta da dieci persone ed è comandata da un sergente. La squadra fa parte di un plotone di circa cinquanta persone, e tre plotoni compongono una compagnia. Nella tua compagnia 8 uomini su 10 sono della tua città. Alcuni li conosci di vista.",
    },
    {
        name: "Karl",
        story: "Sei nato nel 1907 nella periferia di Amburgo. Appena sei diventato abbastanza grande da prendere la patente tuo padre è morto e hai ereditato il suo camion, e con questo il suo lavoro. Da allora hai viaggiato molto per la Germania e per i paesi confinanti, trasportando pesce. Ami molto la musica e hai un discreto talento per il violino, grazie al quale hai spezzato molti cuori sulle tue rotte di viaggio. Il giorno del tuo ventiseiesimo compleanno Hitler ha preso il potere. Quella sera hai festeggiato in un clima goliardico, affascinato dalla capacità del nazismo di offrire un futuro migliore a tutti i tedeschi e dalla sua capacità di creare finalmente unità nazionale. In quello stesso anno è nato anche il tuo primo figlio, Oscar. Lo scoppio della guerra nel 1939 ha mandato in crisi gli scambi commerciali e, di conseguenza, il tuo lavoro. Siamo nel 1942. Ormai hai 35 anni e 4 figli e fai un passo importante: ti arruoli nella polizia e contemporaneamente decidi di prendere la tessera del partito nazionalsocialista, cosa che non avevi mai fatto perché non ne avevi mai sentito la necessità (e nessuno ti aveva mai obbligato a farlo). Il tuo battaglione si chiama Battaglione 101. La tua squadra è composta da dieci persone ed è comandata da un sergente. La squadra fa parte di un plotone di circa cinquanta persone. Sai che nel tuo plotone sono quasi tutti della tua città e dei paesi vicini, anche se non conosci personalmente nessuno di loro. Sei uno dei più giovani e sai bene che se vuoi fare carriera devi rigare dritto.",
    },
    {
        name: "Bruno",
        story: "Sei nato nel 1905 ad Amburgo. I tuoi genitori sono morti che tu eri molto piccolo. Sei stato cresciuto dai tuoi zii materni chegestivano una birreria. Fin da ragazzino hai dato una mano con il lavoro, trascurando la scuola: tipiaceva ascoltare i racconti dei clienti, molti dei quali erano marinai che viaggiavano in lungo e in largo. Ricordi benissimo il 1918: tu avevi 13 anni e molti avventori della birreria erano reduci sconvolti dall'aver visto e combattuto la prima guerra mondiale. Quella di cameriere è diventata presto la tua professione. Proprio in birreria hai conosciuto quellache sarebbe diventata tua moglie, Anne, una donna coraggiosa, che crede nella democrazia e che non si è mai schierata con i nazisti. Ma nel frattempo Hitler ha preso il potere. Dopo 5 anni di regime, nel 1938, sperando di poter fare carriera, hai deciso in accordo con Anne di arruolarti nella polizia, anche per evitare di andare al fronte. Ti hanno assegnato al Battaglione 101. Tuttavia i tuoi calcoli si sono rivelati errati: meno di due anni dopo ti hanno inviato nella Polonia occidentale occupata dall'esercito tedesco per gestire, insieme al tuo battaglione, le “azioni di ricolonizzazione”. Si trattava di spostare centinaia di famiglie di “nemici del popolo” (ebrei, zingari, polacchi) per fare spazio ai tedeschi che avrebbero voluto emigrare. All'inizio hai pensato che fosse una buona idea, finché non hai assistito, sebbene da lontano, alle prime fucilazioni. Due tuoi compagni hanno ucciso a sangue freddo una coppia di anziani ebrei. Tu ti sei reso conto che questo compito ti dà il mal di pancia, ma hai promesso a te stesso che ad Anne non avresti raccontato nulla. Per fortuna è arrivato presto il momento di tornare a casa da lei. Nei mesi successivi il battaglione è stato completamente riorganizzato. Ora siamo nel 1942 e la tua squadra è composta da dieci poliziotti. Ne conosci solo uno, Peter, con il quale hai condiviso l'esperienza in Polonia. Degli otto nuovi, 5 sono di Amburgo come te e hanno quasi tutti la tua età.",
    },
    {
        name: "Heinz",
        story: "Sei nato nel 1904 ad Amburgo. Hai presto ereditato da tuo padre l'impresa di legname di famiglia: una grande responsabilità per un ragazzo di 18 anni. Questo ti ha reso un gran lavoratore: sei pragmatico e non ti piacciono le persone che perdono tempo a parlare.  Hai accolto con fastidio l'ascesa al potere del nazismo nel 1933 ma 4 anni dopo, per non avere grane, hai aderito al partito. Nel 1939 hai deciso di arruolarti nella polizia e di lasciare momentaneamente a tua moglie il compito di mandare avanti l'impresa di famiglia. La guerra è iniziata e tu avresti voluto stare lontano dal fronte, per questo ti hanno consigliato di arruolarti nel “Battaglione di polizia 101”. La tua attitudine al lavoro però ti ha reso presto indispensabile: dopo pochi mesi dal tuo arrivo sei stato inviato nella Polonia appena occupata per fare da autista al tuo comandante: il maggiore Trapp. Un anno dopo hai fatto richiesta di congedo per tornare a casa, ma ti hanno spedito a sorpresa a un corso di addestramento per ufficiali. Nel novembre del 1941 sei stato nominato tenente e l'anno successivo ti hanno assegnato al comando del primo plotone della prima compagnia. Siamo nel 1942: hai 38 anni, comandi circa cinquanta uomini, la maggior parte dei quali sono comete di Amburgo, anche se non ne conosci quasi nessuno. Sopra di te nella scala gerarchica c'è il comandante della compagnia e tutti siete comandati dal maggiore Trapp, che hai la fortuna di conoscere personalmente. Ti senti sicuro di te perché, a differenza di molti dei tuoi colleghi e sottoposti, hai un'attività fiorente che ti aspetta a casa, e non hai bisogno di fare carriera.",
    },
];
